/*
export const data = {
  products: [
    {
      id: '1',
      name: 'Nezuko figure',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 2,
      rating: 4.5,
      numReviews: 5,
      size: 15,
      description: 'Nezuko from demon slayer',
    },
    {
      id: '2',
      name: 'Itachi figure',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 6,
      rating: 5.0,
      numReviews: 10,
      size: 15,
      description: 'Itachi from naruto series',
    },
    {
      id: '3',
      name: 'Son Goku figure',
      image: '/images/p3.jpg',
      price: 125,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      size: 15,
      description: 'Son Goku from Dragon Ball',
    },
    {
      id: '4',
      name: 'Naruto',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 3,
      rating: 3.0,
      numReviews: 11,
      size: 15,
      description: 'Naruto from Naruto Shippuden',
    },
    {
      id: '5',
      name: 'Kaneki',
      image: '/images/p5.jpg',
      price: 90,
      countInStock: 2,
      rating: 2.5,
      numReviews: 20,
      size: 15,
      description: 'Kaneki from Tokyo Ghoul',
    },
    {
      id: '6',
      name: 'Asta',
      image: '/images/p6.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 4,
      size: 15,
      description: 'Asta from Black Clover',
    },
    {
      id: '7',
      name: 'Yoh Asakura',
      image: '/images/p7.jpg',
      price: 150,
      countInStock: 0,
      rating: 3.5,
      numReviews: 15,
      size: 15,
      description: 'Yoh Asakura from Shaman King',
    },
    {
      id: '8',
      name: 'Sukuna',
      image: '/images/p8.jpg',
      price: 300,
      countInStock: 2,
      rating: 4.5,
      numReviews: 1,
      size: 25,
      description: 'Sukuna from Jujutsu Kaisen',
    },
  ],
}
*/